server:
  port: 8081
  ssl:
    enabled: false
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/templatedb?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: validations

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
     org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicTypeDescriptor: TRACE

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days