server:
  port: 8081
  ssl:
    enabled: false
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: validations

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
     org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicTypeDescriptor: TRACE

application:
  security:
    jwt:
      secret-key:  # secret key
      expiration:   # a day
      refresh-token:
        expiration:   # 7 days